### ISSUE TITLE
Fileapi safari 5.1.7 issue

### ISSUE THREAD

**Issue by syedin** [RubaXa/jquery.fileapi#111]
jquery.fileapi.js:1305TypeError: 'undefined' is not an object (evaluating 'img.width')
All files are the latest.

                 $('#profile_crop').on('shown.bs.modal', function (overlay){
                    $(overlay).on('click', '.js-upload', function (){
                        $('#profile_crop').modal('hide');
                        $('#userpic').fileapi('upload');
                    });
                    $('.js-img', overlay).cropper({
                        file: file,
                        bgColor: '#fff',
                        maxSize: [600, 400],
                        minSize: [100, 100],
                        selection: '90%',
                        onSelect: function (coords) {
                            $('#userpic').fileapi('crop', file, coords);
                        }
                    });
                });
                $('#profile_crop').modal('show');

**Comment by imbalance-hero** [comment]
Здравствуйте. У меня этот же баг и причину нашел. В начале неверно были указаны пути в конфиге к подгружаемым файлам (staticPath), после этого скрипт стал работать через раз. Если при наведении на кнопку в конфигах появляется следующие записи: http://my.jetscreenshot.com/7950/20150105-mjid-50kb.jpg , то загрузка идёт через флеш-плеер http://my.jetscreenshot.com/7950/20150105-rqex-50kb.jpg , который отлично работает, только mime-type "application/octet-stream" и имя отправляемой переменной $_FILES['undefined'], если логов нет, то загрузка файла осуществляется через стандартную выборку файла браузера http://my.jetscreenshot.com/7950/20150105-a4ra-72kb.jpg и ругается на img.width.

В начале я думал, что определяется способ, через который загружать файл при наведении мыши на кнопку, но это совсем не так, сейчас картина следующая:
http://my.jetscreenshot.com/7950/20150105-h3d3-17kb.jpg
http://my.jetscreenshot.com/7950/20150105-ibwd-13kb.jpg
То есть часть кнопки воспринимается как Флеш, а часть - как HTML-input, в моём случае первые 10-20px сверху идут html, а ниже уже Флеш-кнопка. Мне кажется, что дело в том, что флеш-кнопка неверно наложилась поверх HTML-кнопки.

**Comment by RubaXa** [comment]
Поддержка Safari 5.1.7 под Windows официально прекращена три года. Я его не поддерживаю примерно год, если есть желание, присылайте  PR, но у меня нет времени на этот браузер, увы.
