### ISSUE TITLE
Query String Parameters not allowed on POST requests.

### ISSUE THREAD

**Issue by lostincode** [RubaXa/jquery.fileapi#113]
Hi,

I'm trying to use this plugin to upload to AWS S3 but it does not allow the '?fileapiXXX' in the query string. I looked on the main repo (https://github.com/mailru/FileAPI/issues/116) and it says to include 'cache:true' but this plugin does not seem to allow it?

Any way to remove the query string appended to the upload url?

Thanks

**Comment by RubaXa** [comment]
Try dev-branch & use `cache: true` option.

**Comment by lostincode** [comment]
@RubaXa this worked if you want to tag a version. Sorry for late reply.
