### ISSUE TITLE
how to handle error codes?

### ISSUE THREAD

**Issue by scooterlord** [RubaXa/jquery.fileapi#114]
Hello! thanks for the excellent plugin!

On the onselect example you show the list or errors. How can these be used?

Also, concerning filtering image files, how do we give an error if the selected files aren't on our list?

Thanks for your time, I am certain writing more specific examples will help heaps!

**Comment by RubaXa** [comment]
1. `onSelect` — https://github.com/RubaXa/jquery.fileapi#onselectfunctionevtevent-datafilesobject
2. `onFileComplete` — https://github.com/RubaXa/jquery.fileapi#onfilecompletefunctionevtevent-uievtobject

**Comment by scooterlord** [comment]
I read the readme but it's not clear enough. Errors have to be set in some way to produce alerts?

**Comment by RubaXa** [comment]
No, you need to handle them yourself, the plugin does not display error, ex:
```js
onSelect: function (evt, data){
    if (data.other.length) {
        alert(data.other.length + ' files do not come under the requirements.')            
    
        // Details
        $.each(data.other, function (i, file) {
            var details = file.errors;
            
            if (details) {
                if (details.maxSize) {
                    alert(file.name + ' — exceeds the maximum file size');
                }
                
                if (details.minWidth) {
                    alert(file.name + ' — width of the image is smaller than the specified');
                }
                
                // and etc
            }
        });
    }
}
```

**Comment by scooterlord** [comment]
Thanks! You should really add this to the readme.md!
