### ISSUE TITLE
Несколько полей файлов на один скрипт?

### ISSUE THREAD

**Issue by xtcsvirus** [RubaXa/jquery.fileapi#115]
Взял пример с этого сайта "http://rubaxa.github.io/jquery.fileapi/", а именно "Simple button". Задача стоит в том, чтобы вставить "несколько" таких кнопок как там используя всего лишь одну JS базу.
Просто продублицировать HTML код, заменить ID на CLASS, к сожалению не прокатывает, ибо скрипт потом при нажатии на одну кнопку, заменяет все (как я понимаю родительский THIS объект просто игнорируется). Как можно реализовать такую возможность?

Спасибо.

**Comment by RubaXa** [comment]
Создайте пример на jsbin.com того, что вы пытаетесь сделать.

**Comment by xtcsvirus** [comment]
Простейший копи-паст с вашей страницы, не ругайте сильно.
http://jsbin.com/huyeyuziki/2/edit
Но принцип именно такой.

**Comment by xtcsvirus** [comment]
Константин, есть ли решение данной проблемы или же путь как это можно решить?
Спасибо.

**Comment by RubaXa** [comment]
Извиняюсь, что не ответил сразу, сейчас нет возможности даже ознакомиться с примером, только после 11.

> Константин, есть ли решение данной проблемы или же путь как это можно решить?
> Спасибо.

**Comment by xtcsvirus** [comment]
Буду очень благодарен! Хорошего рабочего дня :+1:

**Comment by RubaXa** [comment]
Сейчас праздники, так что 11 это число ;]

> Буду очень благодарен! Хорошего рабочего дня 
>

**Comment by RubaXa** [comment]
Попробуйте dev-ветку.

**Comment by xtcsvirus** [comment]
Протестировал на примере выше, работает отлично. Более тщательно буду тестировать позже. Большое спасибо! :)
