### ISSUE TITLE
Отладка fileapi

### ISSUE THREAD

**Issue by alexieze** [RubaXa/jquery.fileapi#116]
Константин доброго времени суток, скачал ваше расширение для загрузки файлов, очень понравилось, решил использовать его повсеместно во всем проекте, можете подсказать как включать вывод в консоль браузера ответов от сервера. Заранее спасибо.

**Comment by RubaXa** [comment]
Включите дебаг режим, смотрите Console: http://mailru.github.io/FileAPI/#ru/FileAPI.setup

P.S. Так же вы можете открыть Network и там смотреть все запросы, без debug

**Comment by alexieze** [comment]
Спасибо огромное!
