### ISSUE TITLE
Работа с загруженными файлами

### ISSUE THREAD

**Issue by kolesnikova-tavi** [RubaXa/jquery.fileapi#118]
Добрый день!
1) Хотелось бы в files передавать только список ссылок, а все остальные данные (тип, размер, ширина, высота) получать с помощью плагина, как это делается при выборе. Есть ли такая возможность?
2) Было бы неплохо иметь событие (например onInit), в котором можно пробежаться как в onSelect по файлам, переданным параметром files. Хочется выделить данные файлы в доме.
3) Есть ли возможность добавлять уже загруженные файлы на сервер обратно в очередь загрузки? При сохранении файла создаются ещё два (imageTransform), на размеры которых влияют внешние факторы. Поэтому при повторном открытии страницы с уже загруженными файлами, либо просто после загрузки пользователь может изменить параметры, и понадобится загрузить снова какой-нибудь из этих двух файлов.
Спасибо!

**Comment by RubaXa** [comment]
1. Нет
2. Да, можно добавить такое событие
3. Нет, такой возможности нету.

**Comment by kolesnikova-tavi** [comment]
Так жаль. Придётся работу с картинками переносить на сервер.
Что касается загрузки, всё отлично! Спасибо!
