### ISSUE TITLE
Пере-инициализация плагина. Не нашел инфы. Неужели невозможно?

### ISSUE THREAD

**Issue by RWpolyakov** [RubaXa/jquery.fileapi#119]
Собственно, сабж.

Требуется после определенного действия поменять количество максимального количества загружаемых файлов. Обычным способом (как со всеми плагинами) не работает.

Есть возможность такого вообще? :)
Спасибо!

**Comment by RubaXa** [comment]
1. Что такое  обычный способ?
2. Чем не устравивает `$('...').fileapi('maxFiles', XXX)`

**Comment by RWpolyakov** [comment]
Я извинияюсь, у меня был глюк, уже все работает, не успел отписаться)) Спасибо за быструю реакцию!
