### ISSUE TITLE
Загрузка выбранной картинки как в исходном виде так и в кропнутом одновременно плюс детали...

### ISSUE THREAD

**Issue by chmig29fulcrum** [RubaXa/jquery.fileapi#120]
Добрый день.
Большое спасибо за плагин, он очень быстро стал популярным. Я пытаюсь создать апликацию на фреймворке yii2. Ваш FileAPI был адаптирован к yii2, vova07 написал "обертку" для него
https://github.com/vova07/yii2-fileapi-widget

Все работает как часы, но только по одному файлу. 
Загружается либо файл оригинал, либо его кроп.
А мне нужно чтоб одновременно закачивались :
1. Оригинальная картинка.
2. кропнутая картинка
3. еще одна ресайзнутая картинка от кропа.
4. Плюс хотелось бы на все картинки watermark наложить. 

Можете посоветовать в каком направлении копать ?

**Comment by RubaXa** [comment]
- `imageOriginal:Boolean` — https://github.com/mailru/FileAPI#imageoriginalboolean
 - `imageTransform:Object` — https://github.com/mailru/FileAPI#imagetransformobject

**Comment by chmig29fulcrum** [comment]
Я пытался отправлять imageOriginal но не получается

'settings' => [
                'url' => ['/users/fileapi-upload'],
                'imageOriginal' => true
            ],
            'crop' => true,
            'cropResizeWidth' => 100,
            'cropResizeHeight' => 100,

**Comment by chmig29fulcrum** [comment]
Походу обнаружил что в current setting-ах у вас imageOriginal итак выставлен в true.
Однако когда после всех манипуляций, в папке сохраняется только кропнутая картинка :(

**Comment by chmig29fulcrum** [comment]
В функции upload
нашел место
, imageOriginal: opts.imageOriginal
заменил его прямо на
, imageOriginal: true
Всеравно закачивается только кропнутая картинка:( Оригинальная картинка в пролете :(

**Comment by chmig29fulcrum** [comment]
В функции Upload закинул проверочный alert с выводом на экран содержимого uploadOpts.imageOriginal
В момент проведения кропа Алертит на экран  "true". Однако оригинальная картинка не сохраняется, только кропнутая версия :(

**Comment by RubaXa** [comment]
Просите, сейчас занят, только вечером (после 22) посмотрю, что да как.

**Comment by chmig29fulcrum** [comment]
Ок, заранее спасибо :)

**Comment by RubaXa** [comment]
Вспомнил, там есть одна хитрость, нужно сделать так:
```js
imageTransform: {
    cropped: {}
}
```
Тогда на сервер будут отправлены два изображения.

**Comment by RubaXa** [comment]
@chmig29fulcrum ?

**Comment by chmig29fulcrum** [comment]
спасибо за комент, просто как оказалось надо саму надстройку автора vova07 менять, так как она написана только для работы с одним файлом картинки. Учитывая то что я пока скажем так начинающий во всем этом, даже не знаю сколько времени мне понадобится чтобы все осилить, поэтому извиняюсь но пока еще не дошел до решения вопроса. Обещаю если будет какоето продвижение вперед - обязательно запостить тут. Еще раз спасибо за подсказку.

**Comment by chmig29fulcrum** [comment]
немножко глупый вопрос может быть но:
пытаюсь разобраться в коде...
Вобщем на стороне надстройки есть такой код обработчика
    public function run()
    {
        if (Yii::$app->request->isPost) {
            $file = UploadedFile::getInstanceByName($this->paramName);
            $model = new DynamicModel(compact('file'));
            $model->addRule('file', $this->_validator, $this->validatorOptions)->validate();

            if ($model->hasErrors()) {
                $result = [
                    'error' => $model->getFirstError('file')
                ];
            } else {
                if ($this->unique === true && $model->file->extension) {
                    $model->file->name = uniqid() . '.' . $model->file->extension;
                }
                if ($model->file->saveAs($this->path . $model->file->name)) {
                    $result = ['name' => $model->file->name];
                   
При html
        FileAPI::className(),
        [
            'settings' => [
                'url' => ['/users/fileapi-upload'],
            ],
            'crop' => true,
            'cropResizeWidth' => 100,
            'cropResizeHeight' => 100,
        ]
обрабатывается превьюшная картинка.

Если сделать 
        FileAPI::className(),
        [
            'settings' => [
                'url' => ['/users/fileapi-upload'],
                'imageTransform' => ['cropped' => []]

            ],
            'crop' => true,
            'cropResizeWidth' => 100,
            'cropResizeHeight' => 100,
        ]
    );
Тогда записывается файл содержащий изображение целиком.
Это потому наверно что первым идут данные по целой необрезаной картинке ?

Можете подсказать как JS передает данные PHP чтобы понять как их выцепить со стороны PHP ?

Заранее извиняюсь если вопрос задан некоректно, просто я пока еще сильно начинающий во всем этом, а тут сразу приходиться разбираться в двух продуктах одновременно :(

**Comment by rdeanar** [comment]
@chmig29fulcrum, возможно, вам больше подойдет вот эта обертка:
https://github.com/rdeanar/yii2-file-processor/tree/develop

В ней есть то, что вам нужно. Для каждого типа изображений можно задать конфиг с неограниченным количеством вариаций (ограничивается только размером необходимой оперативной памяти). 
В вариации можно указать размер изображения, режим ресайза (inset, outbound) и качество сохраняемого изображения. В планах водяной знак и кроп (хотя на данный момент многого можно добиться комбинацией размера и режима ресайза).

Обертка реализована используя немного иной подход, используется отдельная таблица в бд для данных о файле и привязки файлов к моделям, это позволяет делать мультиаплоад и удобно сортировать последовательность файлов.

В данный момент довольно много отличий в ветке develop по сравнению с master. В ближайшее время ожидается релиз. Актуальную версию можно установить прописав ссылку на репозиторий в конфиге composer, либо дождаться релиза.

**Comment by chmig29fulcrum** [comment]
Большое спасибо! Обязательно попробую. Очень надеюсь на реализацию кропа и водяного знака. Это былобы тем максимум который мне нужен на данный момент.

**Comment by chmig29fulcrum** [comment]
попытка апдейтнуть композер "deanar/yii2-file-processor": "*" выдала что такого пекеджа вообще нет.

**Comment by rdeanar** [comment]
@chmig29fulcrum очень странно, должно работать, только что перепроверил у себя.

В секцию `require` в файле `composer.json` можно вставить 
`"deanar/yii2-file-processor": "dev-develop"`
тогда установится из девелоперской ветки.

**Comment by chmig29fulcrum** [comment]
@RubaXa можно узнать что и какими параметрами будет посылать js на сервер при варианте
    FileAPI::className(),
    [
        'settings' => [
            'url' => ['/users/fileapi-upload'],
            'imageTransform' => ['cropped' => []]
        ],
        'crop' => true,
        'cropResizeWidth' => 100,
        'cropResizeHeight' => 100,
    ]
);

? Чтоб понять что принимать и как обработать.

**Comment by chmig29fulcrum** [comment]
@RubaXa Насколько я понял в paramName приходит название файла.
paramName:String

А если у нас два файла, кропнутый и оригинал, то как оба названия пойдут ? массивом или как ? как их выцеплять со стороны сервера ?

**Comment by chmig29fulcrum** [comment]
Походу наверно так писать неправильно  ?  'imageTransform' => ['cropped' => []]

Наверно надо написать  так ? или както иначе ? Чтоб и оригинальная картинка пошла, и кропнутый вариант.
FileAPI::className(),
[
'settings' => [
'url' => ['/users/fileapi-upload'],
'imageOriginal' => true
'imageTransform' => ['cropped' => [
'cropResizeWidth' => 100,
'cropResizeHeight' => 100,
]]
],
'crop' => true,
]
);

**Comment by chmig29fulcrum** [comment]
@RubaXa ?

**Comment by RubaXa** [comment]
Ну я же написал, достаточно определить
```js
imageTransform: {
    cropped: {}
}
```

И на сервер будут отправлены два изображения:
 - fileParamName[original]
 - fileParamName[cropped]

**Comment by chmig29fulcrum** [comment]
Я просто не совсем точно понимаю как именно это надо прописать.
Не могли бы вы пример привести при условии что нужна картинка оригинал + кропнутая картинка 100x100 ? 
Извните если вопрос банальный :)

**Comment by RubaXa** [comment]
```js
$('#uploader').fileapi({
  url: './ctrl.php',
  autoUpload: true,
  accept: 'image/*',
  imageTransform: {
    cropped: {}
  },
  onSelect: function (evt, data) {
       $(this).fileapi("crop", data.files[0], { x: 0, y: 0, w: 100, h: 100 });
  }
});
```

**Comment by chmig29fulcrum** [comment]
@RubaXa Добрый день!
Оставил попытки приручить ту надстройку и пытаюсь по новой прикрутить уже
jqueryFileAPI к моему проэкту.
посмотрел примеры http://rubaxa.github.io/jquery.fileapi/
Остановился на Userpic + crop варианте.
Но интересна серверная часть. 
У вас указан ctrl.php как обработчик запросов JS.
Не могли бы вы показать как и что происходит со стороны сервера ?

**Comment by RubaXa** [comment]
Там нет никакой обработки:
https://github.com/mailru/FileAPI/blob/master/server/ctrl.php

**Comment by rdeanar** [comment]
@chmig29fulcrum Я добавил в свой модуль поддержку водяных знаков, которые были вам нужны, можете не городить велосипед и воспользоваться готовым решением.
https://github.com/rdeanar/yii2-file-processor/tree/develop

**Comment by chmig29fulcrum** [comment]
Я так понимаю у вас пока все еще нет кропа, а он мне очень нужен в первую очередь:(

**Comment by rdeanar** [comment]
@chmig29fulcrum В моем решении реализован вариант userpic + crop из коробки.

Если нужно что-то другое, вы можете написать пример, я в свою очередь скажу возможно ли это реализовать имеющейся функциональностью. Если приведенный пример может оказаться востребованным, то я его реализую.

**Comment by chmig29fulcrum** [comment]
Большое спасибо, сижу изучаю :)

**Comment by chmig29fulcrum** [comment]
@RubaXa итак пробую просто подключить jqueryAPI подключил к страничке
```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
<script>
    window.FileAPI = {
          debug: false // debug mode
        , staticPath: '/js/jquery.fileapi/FileAPI/' // path to *.swf
    };
</script>
<script src="/js/jquery.fileapi/FileAPI/FileAPI.min.js"></script>
<script src="/js/jquery.fileapi/FileAPI/FileAPI.exif.js"></script>
<script src="/js/jquery.fileapi/jquery.fileapi.min.js"></script>
```
Далее в старничку вставил то что было по примеру
```
<div id="uploader">
    <div class="js-fileapi-wrapper">
        <input type="file" name="files[]" />
    </div>
    <div data-fileapi="active.show" class="progress">
        <div data-fileapi="progress" class="progress__bar"></div>
    </div>
</div>
<script>
    jQuery(function ($){
        $('#uploader').fileapi({
            url: './ctrl.php',
            autoUpload: true,
            accept: 'image/*',
            multiple: true,
            maxSize: FileAPI.MB*10 // max file size
        });
    });
</script>
```
Но ни css не цепляется html элементам, пришлось его самому прикрутить.
Ни jcropя так понимаю не прикручивается никак,
сам js работает, я на клик по ```#uploader``` прикрутил alert и он выполняется исправно. Но при этом после выбирания файла не запускается окошко с кроповой решеткой.

Тоесть я явно чтото не так делаю, можете подсказать в чем проблема ?

**Comment by chmig29fulcrum** [comment]
И еще банальный вопрос, что происходит тогда в ctr и php.class файлах которые лежат на сервере ? Разве не на стороне сервера происходит физический upload и обработка файлов ?

**Comment by RubaXa** [comment]
На сервере вы должны принять файл и сохранить его в нужную категорию.

**Comment by chmig29fulcrum** [comment]
спасибо
