### ISSUE TITLE
Get the image src after crop

### ISSUE THREAD

**Issue by amitabhaghosh197** [RubaXa/jquery.fileapi#130]
Hi,
It's a great plugin. Thanks for publishing. I am using this plugin for the first time. But I am in a problem.
 I am using the Userpic + crop option from this plugin. What I see after cropping the image is converted into canvas. But due to my requirement I want to get the image source instead of canvas which I want to send to my database through ajax. But since it is in canvas I am finding it difficult to get the image src. Can you please suggest how would I get the img src path after cropped??

Thanks in advance.

**Comment by Elizabetta1973** [comment]
Tuve ese problema y lo que hice fue comentar la línea 341 en jquery.fileapi.js:

// Reset input
//FileAPI.reset(evt.target);
