### ISSUE TITLE
Получение ответа от сервера

### ISSUE THREAD

**Issue by dmitrychel** [RubaXa/jquery.fileapi#132]
После загрузки файла сервер возвращает ответ

```
FileAPI::makeResponse(array(
          'status' => FileAPI::OK
        , 'statusText' => 'OK'
        , 'body' => $json
), $jsonp);
```
Каким образом я могу получить этот ответ через jquery на странице и правильно ли выбрано для этого событие `onFileComplete` ?
``` 
$('#userpic').fileapi({
onSelect:
   //загрузка
onFileComplete: function (){
   //распарсить ответ
    }
})
```

**Comment by RubaXa** [comment]
https://github.com/RubaXa/jquery.fileapi#onfilecompletefunctionevtevent-uievtobject

**Comment by dmitrychel** [comment]
Огромное Вам спасибо!
я искал ответ не один час
