### ISSUE TITLE
Как загружать файлы изображений на сервер без каких-либо преобразований?

### ISSUE THREAD

**Issue by MisteryX** [RubaXa/jquery.fileapi#133]
Проблема в том, что даже если не указывать imageTransform, файлы изображений проходят какую-то лишнюю обработку и на сервер приходят явно в изменённом виде. Форматы типа svg, gif, ico и любые другие не jpg/png зачем-то явно преобразуются в png.

Как заставить плагин отправлять файлы изображений в неизменном первозданном виде без преобразований?

**Comment by RubaXa** [comment]
Указать `imageAutoOrientation: false`

**Comment by RubaXa** [comment]
Это как временное решение, а так задача стоит, но времени нет https://github.com/mailru/FileAPI/issues/303

**Comment by MisteryX** [comment]
Огромное, спасибо за плагин и оперативный ответ

**Comment by keltstr** [comment]
в исходниках указано так, но не работает:
            imageTransform:0,
            imageOriginal:true,
а, это работает:
            imageAutoOrientation: false
