### ISSUE TITLE
Can not upload （IE8）

### ISSUE THREAD

**Issue by supermanzero** [RubaXa/jquery.fileapi#135]
log: (js -> flash).getFileInfo: [object Object]
log: (flash -> js).log: parseCmd, command: getFileInfo
log: (flash -> js).log: getFileInfo, fileID: 1429673510211892, callback: FileAPI.Flash._fn.fileapi142967342099815
log: (flash -> js).log: ImageFactory no overlay provided
log: (flash -> js).log: getFileInfo complete, success = true
log: (flash -> js).log: Uncaught error: ArgumentError: Error #2015

**Comment by RubaXa** [comment]
`Error #2015 Invalid BitmapData` — Flash can not process the image.
