### ISSUE TITLE
.Net

### ISSUE THREAD

**Issue by YTEHOK** [RubaXa/jquery.fileapi#136]
Здравствуйте. Как я понял из доков, путь для сохранения файлов и другие настройки прописываются в классе Server PHP. Подскажите, можно ли как-то прикрутить это к .NET или обойтись без этих настроек?

**Comment by RubaXa** [comment]
Не понял вопроса? Все настройки плагина осуществляются через js, обработчик загрузки файлов определяется при помощи опции `url`.

P.S. Что такое «класс Server PHP»? Вы уверены что не перепутали репозиторий?
